#!/usr/bin/env python3

import os
import sys
import hashlib
import requests


def subdb_hash(filename):
    readsize = 64 * 1024
    with open(filename, 'rb') as f:
        data = f.read(readsize)
        f.seek(-readsize, os.SEEK_END)
        data += f.read(readsize)

    return hashlib.md5(data).hexdigest()


def get_subtitle_name(filename):
    names = filename.split(".")[:-1]
    return ".".join(names) + ".srt"


def download_subtitle(filehash, langs):
    headers = {
        'User-Agent': 'SubDB/1.0 (FuckUA/0.1; http://fuck.ua)'
    }
    payload = {'action': 'download', 'hash': filehash, 'language' : ",".join(langs) }
    r = requests.get('http://api.thesubdb.com', headers=headers, params=payload)
    if r.status_code != 200:
        print("unable to find subtitle =(")
        print("response status code: [{}]".format(r.status_code))
        print("response contents: [{}]".format(r.text))
        return None

    return r.text


if len(sys.argv) <= 1:
    print("usage: {} <video file>".format(sys.argv[0]))
    exit(1)

filename = sys.argv[1]
subname = get_subtitle_name(filename)

if os.path.isfile(subname):
    print("subtitle with name[{}] already exists".format(subname))
    exit(1)

filehash = subdb_hash(filename)

print("file[{}] hash is[{}]".format(filename, filehash))
subtitle = download_subtitle(filehash, ["en"])
if subtitle is None:
    exit(1)

print("downloaded subtitle with success, saving it at file[{}]".format(subname))
with open(subname, 'w') as f:
    f.write(subtitle)

print("success")
